// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/oidc/v3/pkg/op (interfaces: KeyProvider)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	op "github.com/zitadel/oidc/v3/pkg/op"
)

// MockKeyProvider is a mock of KeyProvider interface.
type MockKeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockKeyProviderMockRecorder
}

// MockKeyProviderMockRecorder is the mock recorder for MockKeyProvider.
type MockKeyProviderMockRecorder struct {
	mock *MockKeyProvider
}

// NewMockKeyProvider creates a new mock instance.
func NewMockKeyProvider(ctrl *gomock.Controller) *MockKeyProvider {
	mock := &MockKeyProvider{ctrl: ctrl}
	mock.recorder = &MockKeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyProvider) EXPECT() *MockKeyProviderMockRecorder {
	return m.recorder
}

// KeySet mocks base method.
func (m *MockKeyProvider) KeySet(arg0 context.Context) ([]op.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeySet", arg0)
	ret0, _ := ret[0].([]op.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeySet indicates an expected call of KeySet.
func (mr *MockKeyProviderMockRecorder) KeySet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeySet", reflect.TypeOf((*MockKeyProvider)(nil).KeySet), arg0)
}
